module: src.client.agents.HTTPAgent
parameters:
  name: <% NAME %>
  url: https://api.openai.com/v1/completions
  headers:
    Content-Type: application/json
    Authorization: Bearer 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
  body:
    model: <% NAME %>
    temperature: 0
  prompter:
    name: prompt_string
  return_format: "{response[choices][0][text]}"

