import: definition.yaml

concurrency:
  task:
    dbbench-std: 5
    os-std: 5
  agent:
    llama-2-7b-v0.3.13: 5

assignments: # List[Assignment] | Assignment
  - agent: # "task": List[str] | str ,  "agent": List[str] | str
      - llama-2-7b-v0.3.13
    task:
      - dbbench-std
      - os-std

output: "outputs/{TIMESTAMP}"
