import: definition.yaml

concurrency:
  task:
    dbbench-std: 5
    os-std: 5
  agent:
    vicuna-7b-v1.5: 5

assignments: # List[Assignment] | Assignment
  - agent: # "task": List[str] | str ,  "agent": List[str] | str
      - vicuna-7b-v1.5
    task:
      - dbbench-std
      - os-std

output: "outputs/{TIMESTAMP}"
